name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: ruby ./test/smoke/run.rb
